### PR TITLE
German de_DE_formal

### PR DESCRIPTION
**Pull request by WanielDeiss**
i changed "Du" to "Sie", "Dein" to "Ihr", etc.

### CODE REVIEW

**Comment by maximus80** [comment]
Dankeschön! :-)

**Comment by aristath** [comment]
Should we replace the `de_DE` file with this one? 
`de_DE_formal` is not supported on https://wpcentral.io/internationalization/ so it's not a language that can be selected in WP.
With that in mind, I don't see how a `_formal` language file makes sense. We should either keep the `de_DE` or replace it with this one.

**Comment by WanielDeiss** [comment]
Many germans use the de_DE_formal for the "business german", it makes definitely sense!
WordPress it self and many themes/plugins supports it.

You can here select "de default" and "de formal"
https://translate.wordpress.org/locale/de
https://translate.wordpress.org/locale/de/formal/wp

**Comment by aristath** [comment]
@WanielDeiss I didn't know that, thanks!
In that case it makes perfect sense. 👍

**Pull request merged**
