### PR TITLE
French translations related to the projects

### PR DESCRIPTION
**Pull request by ppezier**

### CODE REVIEW

**Comment by aristath** [comment]
Hello there @ppezier!
Can you please delete the extra space before `:` ?
For example `Compétences requises :` should be `Compétences requises:`.
Once this is done we can merge these 👍

**Comment by ppezier** [comment]
Hello and thank you for your update.
It’s not a mistake: when writing French, we’re supposed to add a hard space before and after each « double » characters (such as ; : ! ? « »).

**Comment by aristath** [comment]
Confirmed: https://www.thoughtco.com/how-to-use-french-punctuation-4086509

> In French, a space is required both before and after all two- (or more) part punctuation marks and symbols, including : ; « » ! ? % $ #

Merging this. 👍

**Comment by aristath** [comment]
regenerated the `.mo` file with the new strings.

**Comment by ppezier** [comment]
👍

**Pull request merged**
